WebApplicationCTDEO/Controllers/TurmasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationCTDEO.Context;
using WebApplicationCTDEO.Models;

namespace WebApplicationCTDEO.Controllers
{
    public class TurmasController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Turmas
        public ActionResult Index()
        {
            var turmas = db.Turmas.Include(t => t.Modalidade);
            return View(turmas.ToList());
        }

        // GET: Turmas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = db.Turmas.Find(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            return View(turma);
        }
        

        // GET: Turmas/Create
        public ActionResult Create()
        {
            Turma turma = new Turma();
            ViewData["Modalidades"] = db.Modalidade.ToList();
            return View(turma);
        }

        // POST: Turmas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TurmaId,Nome,ModalidadeId,Turno,Horario,ListadeDias")] Turma turma)
        {
            turma.Dias = string.Join(",", turma.ListadeDias.ToArray()); //adicionando lista de strings numa string única
            
            ViewData["Modalidades"] = db.Modalidade.ToList();
            if (ModelState.IsValid)
            {
                db.Turmas.Add(turma);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ModalidadeId = new SelectList(db.Modalidade, "ModalidadeId", "Nome", turma.ModalidadeId);
            return View(turma);
        }

        // GET: Turmas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = db.Turmas.Find(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            ViewBag.ModalidadeId = new SelectList(db.Modalidade, "ModalidadeId", "Nome", turma.ModalidadeId);
            return View(turma);
        }

        // POST: Turmas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TurmaId,Nome,ModalidadeId,Dias,Horario")] Turma turma)
        {
            if (ModelState.IsValid)
            {
                db.Entry(turma).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ModalidadeId = new SelectList(db.Modalidade, "ModalidadeId", "Nome", turma.ModalidadeId);
            return View(turma);
        }

        // GET: Turmas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = db.Turmas.Find(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            return View(turma);
        }

        // POST: Turmas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Turma turma = db.Turmas.Find(id);
            db.Turmas.Remove(turma);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationCTDEO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>CTDEO</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Custom styles for this template-->
    <link href="~/Content/CostumStyle.css" rel="stylesheet">
</head>

<body class="sticky-footer" id="page-top">

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 col-xs-1" id="sidebar">
                <div class="list-group">
                    <a data-target="#menu1sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false">
                        <i class="fa fa-fw fa-address-card-o"></i>Alunos
                    </a>
                    <div class="collapse in" id="menu1sub1">
                        <a href="@Url.Action("Cadastrar", "Alunos")" class="list-group-item" data-parent="menu1sub1">Cadastro</a>
                        <a href="@Url.Action("IndexAlunos", "Alunos")" class="list-group-item" data-parent="menu1sub1">Listagem</a>
                    </div>
                    <a href="@Url.Action("Create", "Turmas")" class="list-group-item">
                        <i class="fa fa-fw fa-users"></i>
                        <span class="hidden-sm-down">Turmas</span>
                    </a>
                    <a href="#menu3" class="list-group-item">
                        <i class="fa fa-fw fa-trophy"></i>
                        <span class="hidden-sm-down">Competições</span>
                    </a>
                    <a href="#menu4" class="list-group-item">
                        <i class="fa fa-fw fa-user-circle"></i>
                        <span class="hidden-sm-down">Equipe</span>
                    </a>
                    <a data-target="#menu4sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false">
                        <i class="fa fa-fw fa-table"></i>Finanças
                    </a>
                    <div class="collapse in" id="menu4sub1">
                        <a data-target="#menu4sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false">
                            <i class="fa fa-fw fa-table"></i>Gastos
                        </a>
                        <div class="collapse in" id="menu4sub2">
                            <a href="@Url.Action("Cadastrar", "Gastos")" class="list-group-item" data-parent="menu4sub2">Cadastrar</a>
                            <a href="@Url.Action("Index", "Gastos")" class="list-group-item" data-parent="menu4sub2">Listagem</a>
                        </div>
                        <a data-target="#menu4sub3" class="list-group-item" data-toggle="collapse" aria-expanded="false">
                            <i class="fa fa-fw fa-table"></i>Orçamento
                        </a>
                        <div class="collapse in" id="menu4sub3">
                            <a href="@Url.Action("Cadastrar", "Orcamento")" class="list-group-item" data-parent="menu4sub3">Cadastrar</a>
                            <a href="@Url.Action("Index", "Orcamento")" class="list-group-item" data-parent="menu4sub3">Listagem</a>
                        </div>
                    </div>
                    <a href="#menu4" class="list-group-item">
                        <i class="fa fa-fw fa-area-chart"></i>
                        <span class="hidden-sm-down">Gráficos</span>
                    </a>
                    <a href=”#sidebar” data-toggle=”collapse”>
                        <i class=”fa fa-navicon fa-lg”></i>
                    </a>
                </div>
            </div>


            <main class="col-md-10 col-xs-11">
                <div class="jumbotron-fluid .fill">Sistema Gerencial CTDEO</div>
                <div class="container body-content .container-fluid .content-wrapper">
                    @RenderBody()
                </div>
            </main>
            <footer class="sticky-footer">
                <div class="text-center">
                    <small>Desenvolvido por Tainara Campos</small>
                </div>
            </footer>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="~/Scripts/CustomScripts.js"></script>
</body>
</html>